classification: kicad_footprint
color: ''
description: eda
description_extra: fuseholder_blade_ato_littelfuse_flr_178_6165
description_main: fuse
footprint_id: eda_kicad_footprint_kicad_default_fuse_fuseholder_blade_ato_littelfuse_flr_178_6165
footprint_string:
  attributes: Attributes(type='through_hole', boardOnly=False, excludeFromPosFiles=False,
    excludeFromBom=False)
  autoplaceCost180: None
  autoplaceCost90: None
  clearance: None
  description: Littelfuse fuse holder for ATO/FKS blade fuses, 80V, vertical, 20 x
    6mm, PCB thickness up to 1.5mm, http://www.littelfuse.com/~/media/commercial-vehicle/datasheets/automotive-fuse-holders/ato/littelfuse-fuse-holder-ato-flr-pcb-datasheet.pdf
  entryName: FuseHolder_Blade_ATO_Littelfuse_FLR_178.6165
  filePath: None
  generator: pcbnew
  graphicItems: '[FpLine(start=Position(X=-3.91, Y=-2.06, angle=None, unlocked=False),
    end=Position(X=16.71, Y=-2.06, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=-3.91, Y=4.56, angle=None, unlocked=False),
    end=Position(X=-3.91, Y=-2.06, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=16.71, Y=-2.06, angle=None, unlocked=False),
    end=Position(X=16.71, Y=4.56, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=16.71, Y=4.56, angle=None, unlocked=False),
    end=Position(X=-3.91, Y=4.56, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=-4.1, Y=-2.25, angle=None, unlocked=False),
    end=Position(X=16.9, Y=-2.25, angle=None, unlocked=False), layer=''F.CrtYd'',
    width=None, stroke=Stroke(width=0.05, type=''default'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=-4.1, Y=4.75, angle=None, unlocked=False),
    end=Position(X=-4.1, Y=-2.25, angle=None, unlocked=False), layer=''F.CrtYd'',
    width=None, stroke=Stroke(width=0.05, type=''default'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=16.9, Y=-2.25, angle=None, unlocked=False),
    end=Position(X=16.9, Y=4.75, angle=None, unlocked=False), layer=''F.CrtYd'', width=None,
    stroke=Stroke(width=0.05, type=''default'', color=None), locked=False, tstamp=None),
    FpLine(start=Position(X=16.9, Y=4.75, angle=None, unlocked=False), end=Position(X=-4.1,
    Y=4.75, angle=None, unlocked=False), layer=''F.CrtYd'', width=None, stroke=Stroke(width=0.05,
    type=''default'', color=None), locked=False, tstamp=None), FpLine(start=Position(X=-3.6,
    Y=-1.75, angle=None, unlocked=False), end=Position(X=16.4, Y=-1.75, angle=None,
    unlocked=False), layer=''F.Fab'', width=None, stroke=Stroke(width=0.1, type=''solid'',
    color=None), locked=False, tstamp=None), FpLine(start=Position(X=-3.6, Y=4.25,
    angle=None, unlocked=False), end=Position(X=-3.6, Y=-1.75, angle=None, unlocked=False),
    layer=''F.Fab'', width=None, stroke=Stroke(width=0.1, type=''solid'', color=None),
    locked=False, tstamp=None), FpLine(start=Position(X=16.4, Y=-1.75, angle=None,
    unlocked=False), end=Position(X=16.4, Y=4.25, angle=None, unlocked=False), layer=''F.Fab'',
    width=None, stroke=Stroke(width=0.1, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=16.4, Y=4.25, angle=None, unlocked=False),
    end=Position(X=-3.6, Y=4.25, angle=None, unlocked=False), layer=''F.Fab'', width=None,
    stroke=Stroke(width=0.1, type=''solid'', color=None), locked=False, tstamp=None),
    FpText(type=''user'', text=''${REFERENCE}'', position=Position(X=6.4, Y=1.25,
    angle=0, unlocked=False), layer=''F.Fab'', hide=False, effects=Effects(font=Font(face=None,
    height=1, width=1, thickness=0.15, bold=False, italic=False, lineSpacing=None,
    color=None), justify=Justify(horizontally=None, vertically=None, mirror=False),
    hide=False, href=None), tstamp=None, renderCache=None)]'
  groups: '[]'
  layer: F.Cu
  libraryNickname: None
  locked: 'False'
  models: '[Model(path=''${KICAD8_3DMODEL_DIR}/Fuse.3dshapes/FuseHolder_Blade_ATO_Littelfuse_FLR_178.6165.wrl'',
    pos=Coordinate(X=0, Y=0, Z=0), scale=Coordinate(X=1, Y=1, Z=1), rotate=Coordinate(X=0,
    Y=0, Z=0), hide=False)]'
  pads: '[Pad(number='''', type=''np_thru_hole'', shape=''circle'', position=Position(X=6.4,
    Y=1.25, angle=None, unlocked=False), locked=False, size=Position(X=2.4, Y=2.4,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=2.4, width=None,
    offset=None), layers=[''F&B.Cu'', ''*.Mask''], property=None, removeUnusedLayers=False,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''1'', type=''thru_hole'', shape=''circle'', position=Position(X=0,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=2.2, Y=2.2, angle=None,
    unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4, width=None, offset=None),
    layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True, keepEndLayers=False,
    roundrectRatio=None, chamferRatio=None, chamfer=[], net=None, tstamp=None, pinFunction=None,
    pinType=None, dieLength=None, solderMaskMargin=None, solderPasteMargin=None, solderPasteMarginRatio=None,
    clearance=None, zoneConnect=None, thermalWidth=None, thermalGap=None, customPadOptions=None,
    customPadPrimitives=[]), Pad(number=''1'', type=''thru_hole'', shape=''circle'',
    position=Position(X=0, Y=2.5, angle=None, unlocked=False), locked=False, size=Position(X=2.2,
    Y=2.2, angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''1'', type=''thru_hole'', shape=''circle'', position=Position(X=3.5,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=2.2, Y=2.2, angle=None,
    unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4, width=None, offset=None),
    layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True, keepEndLayers=False,
    roundrectRatio=None, chamferRatio=None, chamfer=[], net=None, tstamp=None, pinFunction=None,
    pinType=None, dieLength=None, solderMaskMargin=None, solderPasteMargin=None, solderPasteMarginRatio=None,
    clearance=None, zoneConnect=None, thermalWidth=None, thermalGap=None, customPadOptions=None,
    customPadPrimitives=[]), Pad(number=''1'', type=''thru_hole'', shape=''circle'',
    position=Position(X=3.5, Y=2.5, angle=None, unlocked=False), locked=False, size=Position(X=2.2,
    Y=2.2, angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''2'', type=''thru_hole'', shape=''circle'', position=Position(X=9.3,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=2.2, Y=2.2, angle=None,
    unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4, width=None, offset=None),
    layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True, keepEndLayers=False,
    roundrectRatio=None, chamferRatio=None, chamfer=[], net=None, tstamp=None, pinFunction=None,
    pinType=None, dieLength=None, solderMaskMargin=None, solderPasteMargin=None, solderPasteMarginRatio=None,
    clearance=None, zoneConnect=None, thermalWidth=None, thermalGap=None, customPadOptions=None,
    customPadPrimitives=[]), Pad(number=''2'', type=''thru_hole'', shape=''circle'',
    position=Position(X=9.3, Y=2.5, angle=None, unlocked=False), locked=False, size=Position(X=2.2,
    Y=2.2, angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''2'', type=''thru_hole'', shape=''circle'', position=Position(X=12.8,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=2.2, Y=2.2, angle=None,
    unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4, width=None, offset=None),
    layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True, keepEndLayers=False,
    roundrectRatio=None, chamferRatio=None, chamfer=[], net=None, tstamp=None, pinFunction=None,
    pinType=None, dieLength=None, solderMaskMargin=None, solderPasteMargin=None, solderPasteMarginRatio=None,
    clearance=None, zoneConnect=None, thermalWidth=None, thermalGap=None, customPadOptions=None,
    customPadPrimitives=[]), Pad(number=''2'', type=''thru_hole'', shape=''circle'',
    position=Position(X=12.8, Y=2.5, angle=None, unlocked=False), locked=False, size=Position(X=2.2,
    Y=2.2, angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=1.4,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[])]'
  path: None
  placed: 'False'
  position: None
  properties: '{''Reference'': ''REF**'', ''Value'': ''FuseHolder_Blade_ATO_Littelfuse_FLR_178.6165'',
    ''Footprint'': '''', ''Datasheet'': '''', ''Description'': ''''}'
  solderMaskMargin: None
  solderPasteMargin: None
  solderPasteRatio: None
  tags: ATO FKS blade fuse holder
  tedit: 65f83759
  thermalGap: None
  thermalWidth: None
  tstamp: None
  version: '20240108'
  zoneConnect: None
  zones: '[]'
manufacturer: ''
part_number: ''
short_name: ''
size: ''
type: kicad_default
