classification: kicad_footprint
color: ''
description: eda
description_extra: samtec_hle_110_02_xx_dv_te_2x10_p2_54mm_horizontal
description_main: connector_samtec_hle_tht
footprint_id: eda_kicad_footprint_kicad_default_connector_samtec_hle_tht_samtec_hle_110_02_xx_dv_te_2x10_p2_54mm_horizontal
footprint_string:
  attributes: Attributes(type='through_hole', boardOnly=False, excludeFromPosFiles=False,
    excludeFromBom=False)
  autoplaceCost180: None
  autoplaceCost90: None
  clearance: None
  description: Samtec HLE .100" Tiger Beam Cost-effective Single Beam Socket Strip,
    HLE-110-02-xx-DV-TE, 10 Pins per row (http://suddendocs.samtec.com/prints/hle-1xx-02-xx-dv-xe-xx-mkt.pdf,
    http://suddendocs.samtec.com/prints/hle-thru.pdf), generated with kicad-footprint-generator
  entryName: Samtec_HLE-110-02-xx-DV-TE_2x10_P2.54mm_Horizontal
  filePath: None
  generator: pcbnew
  graphicItems: '[FpLine(start=Position(X=-1.38, Y=-1.38, angle=None, unlocked=False),
    end=Position(X=24.24, Y=-1.38, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=-1.38, Y=3.92, angle=None, unlocked=False),
    end=Position(X=-1.38, Y=-1.38, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=24.24, Y=-1.38, angle=None, unlocked=False),
    end=Position(X=24.24, Y=3.92, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=24.24, Y=3.92, angle=None, unlocked=False),
    end=Position(X=-1.38, Y=3.92, angle=None, unlocked=False), layer=''F.SilkS'',
    width=None, stroke=Stroke(width=0.12, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=-1.77, Y=-1.77, angle=None, unlocked=False),
    end=Position(X=24.63, Y=-1.77, angle=None, unlocked=False), layer=''F.CrtYd'',
    width=None, stroke=Stroke(width=0.05, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=-1.77, Y=4.31, angle=None, unlocked=False),
    end=Position(X=-1.77, Y=-1.77, angle=None, unlocked=False), layer=''F.CrtYd'',
    width=None, stroke=Stroke(width=0.05, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=24.63, Y=-1.77, angle=None, unlocked=False),
    end=Position(X=24.63, Y=4.31, angle=None, unlocked=False), layer=''F.CrtYd'',
    width=None, stroke=Stroke(width=0.05, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=24.63, Y=4.31, angle=None, unlocked=False),
    end=Position(X=-1.77, Y=4.31, angle=None, unlocked=False), layer=''F.CrtYd'',
    width=None, stroke=Stroke(width=0.05, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=-1.27, Y=-1.27, angle=None, unlocked=False),
    end=Position(X=24.13, Y=-1.27, angle=None, unlocked=False), layer=''F.Fab'', width=None,
    stroke=Stroke(width=0.1, type=''solid'', color=None), locked=False, tstamp=None),
    FpLine(start=Position(X=-1.27, Y=3.81, angle=None, unlocked=False), end=Position(X=-1.27,
    Y=-1.27, angle=None, unlocked=False), layer=''F.Fab'', width=None, stroke=Stroke(width=0.1,
    type=''solid'', color=None), locked=False, tstamp=None), FpLine(start=Position(X=-0.5,
    Y=-1.27, angle=None, unlocked=False), end=Position(X=0, Y=-0.562893, angle=None,
    unlocked=False), layer=''F.Fab'', width=None, stroke=Stroke(width=0.1, type=''solid'',
    color=None), locked=False, tstamp=None), FpLine(start=Position(X=0, Y=-0.562893,
    angle=None, unlocked=False), end=Position(X=0.5, Y=-1.27, angle=None, unlocked=False),
    layer=''F.Fab'', width=None, stroke=Stroke(width=0.1, type=''solid'', color=None),
    locked=False, tstamp=None), FpLine(start=Position(X=24.13, Y=-1.27, angle=None,
    unlocked=False), end=Position(X=24.13, Y=3.81, angle=None, unlocked=False), layer=''F.Fab'',
    width=None, stroke=Stroke(width=0.1, type=''solid'', color=None), locked=False,
    tstamp=None), FpLine(start=Position(X=24.13, Y=3.81, angle=None, unlocked=False),
    end=Position(X=-1.27, Y=3.81, angle=None, unlocked=False), layer=''F.Fab'', width=None,
    stroke=Stroke(width=0.1, type=''solid'', color=None), locked=False, tstamp=None),
    FpText(type=''user'', text=''${REFERENCE}'', position=Position(X=11.43, Y=3.11,
    angle=0, unlocked=False), layer=''F.Fab'', hide=False, effects=Effects(font=Font(face=None,
    height=1, width=1, thickness=0.15, bold=False, italic=False, lineSpacing=None,
    color=None), justify=Justify(horizontally=None, vertically=None, mirror=False),
    hide=False, href=None), tstamp=None, renderCache=None)]'
  groups: '[]'
  layer: F.Cu
  libraryNickname: None
  locked: 'False'
  models: '[Model(path=''${KICAD8_3DMODEL_DIR}/Connector_Samtec_HLE_THT.3dshapes/Samtec_HLE-110-02-xx-DV-TE_2x10_P2.54mm_Horizontal.wrl'',
    pos=Coordinate(X=0, Y=0, Z=0), scale=Coordinate(X=1, Y=1, Z=1), rotate=Coordinate(X=0,
    Y=0, Z=0), hide=False)]'
  pads: '[Pad(number=''1'', type=''thru_hole'', shape=''roundrect'', position=Position(X=0,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=0.19084, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''2'', type=''thru_hole'', shape=''circle'', position=Position(X=0,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''3'', type=''thru_hole'', shape=''circle'', position=Position(X=2.54,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''4'', type=''thru_hole'', shape=''circle'', position=Position(X=2.54,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''5'', type=''thru_hole'', shape=''circle'', position=Position(X=5.08,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''6'', type=''thru_hole'', shape=''circle'', position=Position(X=5.08,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''7'', type=''thru_hole'', shape=''circle'', position=Position(X=7.62,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''8'', type=''thru_hole'', shape=''circle'', position=Position(X=7.62,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''9'', type=''thru_hole'', shape=''circle'', position=Position(X=10.16,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''10'', type=''thru_hole'', shape=''circle'', position=Position(X=10.16,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''11'', type=''thru_hole'', shape=''circle'', position=Position(X=12.7,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''12'', type=''thru_hole'', shape=''circle'', position=Position(X=12.7,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''13'', type=''thru_hole'', shape=''circle'', position=Position(X=15.24,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''14'', type=''thru_hole'', shape=''circle'', position=Position(X=15.24,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''15'', type=''thru_hole'', shape=''circle'', position=Position(X=17.78,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''16'', type=''thru_hole'', shape=''circle'', position=Position(X=17.78,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''17'', type=''thru_hole'', shape=''circle'', position=Position(X=20.32,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''18'', type=''thru_hole'', shape=''circle'', position=Position(X=20.32,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''19'', type=''thru_hole'', shape=''circle'', position=Position(X=22.86,
    Y=0, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[]),
    Pad(number=''20'', type=''thru_hole'', shape=''circle'', position=Position(X=22.86,
    Y=2.54, angle=None, unlocked=False), locked=False, size=Position(X=1.31, Y=1.31,
    angle=None, unlocked=False), drill=DrillDefinition(oval=False, diameter=0.71,
    width=None, offset=None), layers=[''*.Cu'', ''*.Mask''], property=None, removeUnusedLayers=True,
    keepEndLayers=False, roundrectRatio=None, chamferRatio=None, chamfer=[], net=None,
    tstamp=None, pinFunction=None, pinType=None, dieLength=None, solderMaskMargin=None,
    solderPasteMargin=None, solderPasteMarginRatio=None, clearance=None, zoneConnect=None,
    thermalWidth=None, thermalGap=None, customPadOptions=None, customPadPrimitives=[])]'
  path: None
  placed: 'False'
  position: None
  properties: '{''Reference'': ''REF**'', ''Value'': ''Samtec_HLE-110-02-xx-DV-TE_2x10_P2.54mm_Horizontal'',
    ''Footprint'': '''', ''Datasheet'': '''', ''Description'': ''''}'
  solderMaskMargin: None
  solderPasteMargin: None
  solderPasteRatio: None
  tags: connector Samtec HLE top entry
  tedit: 65f83759
  thermalGap: None
  thermalWidth: None
  tstamp: None
  version: '20240108'
  zoneConnect: None
  zones: '[]'
manufacturer: ''
part_number: ''
short_name: ''
size: ''
type: kicad_default
